// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBErliDHn8NAdd-Zyi8HCSBw3zKk-msrj4',
    appId: '1:1084072414990:web:45d601c72d4cd11705d15f',
    messagingSenderId: '1084072414990',
    projectId: 'daytask-a2744',
    authDomain: 'daytask-a2744.firebaseapp.com',
    storageBucket: 'daytask-a2744.firebasestorage.app',
    measurementId: 'G-2HXJCFG2R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Jd0U19YVlClC5dYwa9Xq8DiPr4Q9Jgs',
    appId: '1:1084072414990:android:81628b0676490f7805d15f',
    messagingSenderId: '1084072414990',
    projectId: 'daytask-a2744',
    storageBucket: 'daytask-a2744.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoKjqevdaIDJ1jYRU_on7eSNXrp6LRi8',
    appId: '1:1084072414990:ios:ed99bfa5670e286b05d15f',
    messagingSenderId: '1084072414990',
    projectId: 'daytask-a2744',
    storageBucket: 'daytask-a2744.firebasestorage.app',
    iosBundleId: 'com.example.daytask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoKjqevdaIDJ1jYRU_on7eSNXrp6LRi8',
    appId: '1:1084072414990:ios:ed99bfa5670e286b05d15f',
    messagingSenderId: '1084072414990',
    projectId: 'daytask-a2744',
    storageBucket: 'daytask-a2744.firebasestorage.app',
    iosBundleId: 'com.example.daytask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBErliDHn8NAdd-Zyi8HCSBw3zKk-msrj4',
    appId: '1:1084072414990:web:019b8d4fbecd8bce05d15f',
    messagingSenderId: '1084072414990',
    projectId: 'daytask-a2744',
    authDomain: 'daytask-a2744.firebaseapp.com',
    storageBucket: 'daytask-a2744.firebasestorage.app',
    measurementId: 'G-SKKYM24T2K',
  );
}
